# Common settings
x-wordpress-common: &wordpress-common
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DBUSER}
      WORDPRESS_DB_PASSWORD: ${DBPASS}
      WORDPRESS_DB_NAME: ${DBNAME}
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro

services:
  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "${HOST_BIND}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - wordpress:/var/www/html:ro
    # labels:
      # - "traefik.enable=true"
      # - "traefik.docker.network=proxy"

      #   --- Main HTTPS router for www.<domain> ---
      # - "traefik.http.routers.${SITE_ID}_public.rule=Host(`${WWW_DOMAIN}`)"
      # - "traefik.http.routers.${SITE_ID}_public.entrypoints=websecure"
      # - "traefik.http.routers.${SITE_ID}_public.tls=true"
      # - "traefik.http.routers.${SITE_ID}_public.service=${SITE_ID}_wp"

      #   --- Redirect bare domain â†’ https://www.<domain> ---
      # - "traefik.http.routers.${SITE_ID}_redirect_www.rule=Host(`${DOMAIN}`)"
      # - "traefik.http.routers.${SITE_ID}_redirect_www.entrypoints=websecure"
      # - "traefik.http.routers.${SITE_ID}_redirect_www.tls=true"
      # - "traefik.http.routers.${SITE_ID}_redirect_www.middlewares=${SITE_ID}-to-www"

      # - "traefik.http.middlewares.${SITE_ID}-to-www.redirectregex.regex=^https://${DOMAIN_REGEX}(.*)"
      # - "traefik.http.middlewares.${SITE_ID}-to-www.redirectregex.replacement=https://${WWW_DOMAIN}$1"
      # - "traefik.http.middlewares.${SITE_ID}-to-www.redirectregex.permanent=true"

      #   --- Service: nginx listens on 80 for Traefik ---
      # - "traefik.http.services.${SITE_ID}_wp.loadbalancer.server.port=80"
      # - "traefik.http.services.${SITE_ID}_wp.loadbalancer.server.scheme=http"

  # Actual Wordpress application server
  wordpress:
    <<: *wordpress-common
    image: wordpress:php8.4-fpm
    restart: unless-stopped
    depends_on:
      - db

  # Declare wordpress-cli, but only run it on command
  wordpress-cli:
    <<: *wordpress-common
    image: wordpress:cli
    entrypoint: ["wp"]
    command: ["--info"]

  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DBNAME}
      MARIADB_USER: ${DBUSER}
      MARIADB_PASSWORD: ${DBPASS}
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db-data:/var/lib/mysql

  mariadb-backup:
    image: peetvandesande/mariadb-backup
    deploy:
      resources:
        limits:
          # Don't overconsume resources
          cpus: '0.40'
          memory: 128M
        reservations:
          # But ensure service isn't starved
          cpus: '0.01'
          memory: 8M
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DBNAME}
      MARIADB_USER: ${DBUSER}
      MARIADB_PASSWORD: ${DBPASS}
      CHOWN_UID : 34
      CHOWN_GID : 34
      CHMOD_MODE : "0640"
      COMPRESS : zst
      BACKUP_NAME_PREFIX : wordpress-mariadb-${SITE_ID}
    volumes:
      - /var/backups:/backups
    depends_on:
      - db

  app-backup:
    image: peetvandesande/file-backup
    deploy:
      resources:
        limits:
          # Don't overconsume resources
          cpus: '0.40'
          memory: 128M
        reservations:
          # But ensure service isn't starved
          cpus: '0.01'
          memory: 8M
    environment:
      CHOWN_UID : 34
      CHOWN_GID : 34
      CHMOD_MODE : "0640"
      COMPRESS : zst
      # Keep /local as the last entry of the backup paths to put those files
      # at the end of the archive. This makes the restore process easier.
      # You might not need all files from /local for the restore
      BACKUP_PATHS : "/var/www/html /local"
      BACKUP_NAME_PREFIX : wordpress-data-${SITE_ID}
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/local/nginx/conf.d:ro
      - ./nginx/nginx.conf:/local/nginx/nginx.conf:ro
      - ./wordpress/php/uploads.ini:/local/wordpress/php/uploads.ini:ro
      - ./.env:/local/.env:ro
      - wordpress:/var/www/html:ro
      - /var/backups:/backups

volumes:
  wordpress:
  db-data:
